### ISSUE TITLE
Site Generator / Framework

### ISSUE THREAD

**Issue by timdorr** [rackt/rackt.github.io#1]
Splitting off of rackt/react-router#2259, we're going to need some means by which we build this site. Some of the key features we'll want:

- Markdown support. All the existing documentation is written in this format.
- Leverages the Node ecosystem, which we all have set up already.
- Dog foods @rackt projects, such as Redux and react-router. 

### Gatsby

https://github.com/gatsbyjs/gatsby

##### Pros

- Uses react-router. Runs webpack under the hood, which most of @rackt is familiar with.
- Awesome developer ergonomics (hot reloading).

##### Cons

- New kid on the block. 
- Requires [a lot of stuff](https://github.com/gatsbyjs/gatsby-starter-documentation) in userland currently.

### react-dnd / fixed-data-table

https://github.com/gaearon/react-dnd/tree/master/site
https://github.com/facebook/fixed-data-table/tree/master/site

##### Pros

- Aesthetically pleasing
- Relatively simple in design. 

##### Cons

- No documentation. Might impede the help of others.
- There's a lot of hard coding, which would make supporting multiple projects difficult.

##### Pros

- In theory, would do exactly what we want.
- High degree of customizability.

##### Cons

- We have to do all the heavy lifting.
- May break often.

### Jekyll

http://jekyllrb.com/

##### Pros

- Powers Github Pages. Batteries included.
- React's own site currently uses it.

##### Cons

- Requires Ruby and Python. Doesn't run well on Windows.
- Lots of different syntaxes to keep track of (YAML, Liquid, Ruby)
- Customizable only with a lot of work.

**Comment by gaearon** [comment]
I think helping Gatsby development and tweaking it to our needs is the best solution here.

**Comment by timdorr** [comment]
That's where I'm leaning too, hence I put it first on the list :smile: But if there are other suggestions, I'm all ears.

**Comment by damassi** [comment]
Yup, and it would also allow for the component playground idea (essentially for user debugging) from the other thread.

**Comment by knowbody** [comment]
+1 for Gatsby

**Comment by rajzshkr** [comment]
+1 for Gatsby. shall I help in building the site?

**Comment by mjackson** [comment]
I pushed a basic HTML page just to get something out the door this morning. You guys are free to make it fancier if you'd like. Just seemed like this convo had stalled a bit.

**Comment by timdorr** [comment]
Cool. We'll make it fancy later. Content is more important for now :+1:
