### ISSUE TITLE
When is a project mature enough to be joining rackt.

### ISSUE THREAD

**Issue by jbovenschen** [rackt/rackt.github.io#12]
I don't know if it is a point but i like to raise my issues with the current state of some projects within the  **Rackt** Github organisation.

I use a lot of Rackt projects in current applications myself because for me it is stated when some project is within the this Github organisation it will be mature and it has a small / large community which use it in products in production. But after really looking into some projects I don't really use myself and the issue raised by @taion. I was eager to find out the imaginary bar to know if a project would be mature enough to join this Github organisation.

In the following issue in the scroll behaviour repo rackt/scroll-behavior#34 the following solution is raised to create something like a `rackt-incubator` org** which will make it more clear that the repos under that Github organisation are looking for maintainers and / or are not popular enough to be under the Rackt Github organisation.

The projects i guess that are not really well supported anymore or looking for new maintainers are;
- [react-a11y](https://github.com/rackt/react-a11y) (Would be happy to maintain / or extend this one)
- [scroll-behavior](https://github.com/rackt/scroll-behavior) (as in rackt/scroll-behavior#34)
- [async-props](https://github.com/rackt/async-props)
- [react-router-mega-demo](https://github.com/rackt/react-router-mega-demo)

Please correct me if I am wrong it is just a thing I started to notice and / or read on twitter / Github.

** Don't know if it is an appropriate name for this org because it sounds like it is not mature enough to be an mature Rackt org project. Also there could be projects move back to that org if it is not really relevant or not being maintained anymore.

**Comment by timdorr** [comment]
The best way to get involved is to submit some PRs and get the attention of active members who can review the situation. We're all pretty active on Twitter and Reactiflux, along with being available in tickets too, so getting a hold of someone isn't hard. However, just saying "hey, I'd like to maintain this code" doesn't really hold any weight if there isn't any activity by you to back it up. It doesn't really help anyone if we add maintainers that don't actually do anything :smile:

I don't think there are any hard-and-fast rules for including an existing repo. It's fairly organic right now and pretty rare too. If there is something you have in mind, I would suggest that specifically and we can start a discussion about its inclusion.

**Comment by jbovenschen** [comment]
Sure i understand that you don't just add maintainers to repo's they don't really contribute to! :) For me from now and in the future I want to contribute to more **Rackt** projects and other open source projects I use on daily base. Because I think it is really important to have some stable libraries to build your products upon. At the moment i don't have any libraries / or projects in mind for inclusion. 

I only raised this issue under this repo because I was thinking that more people could have the issues with determine if a repo is maintained stable or not stable at that moment.

But it is clear for me for now and trying to get more of a active contributor from now and in the future! Thanks!

**Comment by knowbody** [comment]
@jbovenschen actually @gaearon mention similar thing here (#8) about showing others at what stage are the libraries under Rackt organization. See the discussion there.
