### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by italoacasas** [rackt/rackt.github.io#3]
Hey guys, like this ?

<img width="1244" alt="screen shot 2015-11-09 at 8 44 13 pm" src="https://cloud.githubusercontent.com/assets/6354455/11052081/eb9ce7fe-8722-11e5-9f24-2af250dba5d6.png">
<img width="1201" alt="screen shot 2015-11-09 at 8 43 23 pm" src="https://cloud.githubusercontent.com/assets/6354455/11052089/fc693c04-8722-11e5-8010-55dc58c9128d.png">

**Comment by knowbody** [comment]
yeah, looks good. We need to start with something, then we can iterate on that :)

**Comment by knowbody** [comment]
can you check out #2 maybe add changes there so we can merge that branch in.

**Comment by timdorr** [comment]
Yeah, if you don't mind, @italoacasas, could you make this a branch off of #2? We can start integrating stuff if it's in PR form.
