### ISSUE TITLE
Content

### ISSUE THREAD

**Issue by italoacasas** [rackt/rackt.github.io#5]
What is the content of this site, the documentation for the router and history?

**Comment by knowbody** [comment]
yes and no. The website will be for the entire Rackt organisation, so will include the info and docs about all our projects

**Comment by italoacasas** [comment]
Ok, but this org, have a lot of projects, and redux have its own site, I was thinking in a website more focus in router and history(links, examples, documentation). Maybe this is not the correct site for that. I really want to contribute, I cant write docu, i am bilingual and my english is really poor, I prefer create the website. let me know, and I do a PR on the night...

**Comment by knowbody** [comment]
I actually did some initial work today, have a look at my PR https://github.com/rackt/rackt.github.io/pull/4

Don't worry too much about the content now. We need Rackt static landing page, which links to our github repo, blog (coming soon), projects (the ones we have on Rackt) and the docs.

Ideally we want to unify the documentations for all the Rackt projects so they have similar format. Talking about the content of the docs, I'd like to have some script that generates new docs on the Rackt page based on the changes on Github, so we do not need to keep track and worry if the docs on the page are the same as the ones on Github.

Thoughts on that @mjackson @ryanflorence @taion @timdorr ?

**Comment by mjackson** [comment]
This site is basically just a manifesto for the rackt org. See #7
