### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by hollandmatt** [rackt/rackt.github.io#6]
Apologies if I'm reporting this in the wrong place, but the "Demo Source" link in http://rackt.org/react-tabs/example/ is currently returning a 404 - I think the correct link href is now https://github.com/rackt/react-tabs/blob/master/examples/basic/app.js

**Comment by knowbody** [comment]
Works just fine for me:

<img width="1275" alt="screen shot 2015-11-17 at 01 14 39" src="https://cloud.githubusercontent.com/assets/3802023/11199772/a53af822-8cc8-11e5-9169-ae33453ed880.png">

**Comment by hollandmatt** [comment]
The Link "Demo Source" in the page points to https://github.com/rackt/react-tabs/blob/master/example/main.js which does not exist.

**Comment by knowbody** [comment]
@mzabriskie could you look into it?
